### ISSUE TITLE
Misc. Issues

### ISSUE THREAD

**Issue by CyborgSun** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#61]
This will be for minor issues I've noticed during various playthroughs, using the pre-release versions, may update over time as more are found:

-Using the Save Both X-Men Optional addon: Jean Grey's skin incorrectly shows as Defaultman in the HUB and Mephisto cage (possible NPC conflict/typo).

-"Eye of the Shadow Queen" objective only works if you portal back to the HUB and talk to Wong before completing Mephisto; If Wong isn't talked to before the end of the mission, then talking to him afterwards doesn't complete the objective.

-A small delay now occurs when talking to Heimdall after getting his horn (a remnant of when there was a new objective there).

-Act 3 HUB: Talking to Hermod, one of the conversation options (Who are the Wrecking Crew) has a section where you can choose "continue..." instead of progressing the convo normally.

-Misspelling in Lizard Vs. Sim ("You're" instead of "Your")

**Comment by ak2yny** [comment]
Thank you for adding these.

**Comment by JordanLeich** [comment]
I tried fixing the Jean Grey Defaultman issue but couldnt figure it out, reverting the JeanSimple code or using JeanGrey still caused the Defaultman to appear.

**Comment by ak2yny** [comment]
Sorry, I had to revert the change for Hermod. If you do it this way, it will be problematic if Thor's on the team, since there will be no answer to continue. I currently don't know a better way to solve this issue, so I'm keeping it as it was previously while keeping the issue checked as completed.

**Comment by ak2yny** [comment]
> I tried fixing the Jean Grey Defaultman issue but couldnt figure it out, reverting the JeanSimple code or using JeanGrey still caused the Defaultman to appear.

Yeah, because it's already fixed: f8cb27fae971a306e2166e8e644f6f5b5a323364

I can't reproduce the issue. Jean appears as she should in the latest version of that mod.

**Comment by JordanLeich** [comment]
> I can't reproduce the issue. Jean appears as she should in the latest version of that mod.

That's odd because I kept having the same issue on my end a few days ago. I'll try retesting with a fresh ocp and that optional magneto reinstall.

**Comment by ak2yny** [comment]
I just realized that Jean doesn't spawn in Strange's hub. That's one file I forgot to update. You have to test it on the cage.

**Comment by ak2yny** [comment]
Fixed: 2ead377a6b330e29125447954f2d657873284c07

**Comment by JordanLeich** [comment]
Jean works properly in all of Mephistos realm now but I cannot get her to spawn in the Sanctum hub area. Is it because I'm extracting to Mephistos realm or do I have to play through the whole entire act as normal or is it something else? Are you having the same issue? @ak2yny

**Comment by ak2yny** [comment]
She only spawns after rescuing her from Arcade and only if she didn't die.

**Comment by JordanLeich** [comment]
> She only spawns after rescuing her from Arcade and only if she didn't die.
> 
> 
> 
> And thanks for testing.

Ok that makes sense then, everything should be working then.

**Comment by JordanLeich** [comment]
reputation points fix in asgard - https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/63b3828fab252a7cac0a13ba88940b652b4a4cae

**Comment by JordanLeich** [comment]
this is the npcstat code corresponding to the Clay Guardian Captain but i cannot find anything that relates to an invulnerability buff.
```
"stats": {
            "body": 1,
            "characteranims": "112_clay_guardian",
            "charactername": "Clay Guardian",
            "combolevel": "medium",
            "deathnode": "deathgen",
            "leadername": "Clay Guardian Captain",
            "leaderskin": 11201,
            "level": 10,
            "mind": 1,
            "name": "ClayGuardian_a",
            "npcdamagescale": 0.75,
            "powerstyle": "ps_clayguardian",
            "scale_factor": 0.8,
            "skin": 11201,
            "sounddir": "clayg_m",
            "standard_pain_only": true,
            "strength": 1,
            "team": "enemy",
            "vuln2_touch_of_death": true,
            "weapon": "wp_clayguardian_daggers",
            "talent": {
                "level": 1,
                "name": "monst_dmg_high"
            },
            "talent": {
                "level": 1,
                "name": "monst_dmg_low"
            },
            "talent": {
                "level": 1,
                "name": "monst_health"
            },
            "talent": {
                "level": 1,
                "name": "fightstyle_villain_Fast"
            },
            "talent": {
                "level": 1,
                "name": "spawnsecond"
            }
        },
```

**Comment by CyborgSun** [comment]
Aren't enemy leaders defined in the map files, and not the npcstat?

**Comment by JordanLeich** [comment]
> Aren't enemy leaders defined in the map files, and not the npcstat?

Ill see if I can find anything

**Comment by CyborgSun** [comment]
Outsider might know something, I know he should be very familiar with how maps work thanks to the EXG work.

**Comment by JordanLeich** [comment]
![image](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/assets/57107961/34e4d20e-c563-4bb4-84a6-0942433d7ba7)
![image](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/assets/57107961/36e6b771-c2ce-413d-8165-7fdae3a9c980)
Good news, I found these 2 code sections for the clay guardian captain (leader). I'm not sure if I should remove this invuln code or replace it with something else.

**Comment by ak2yny** [comment]
The issue is that they also have invulnerability on easy, which they shouldn't (can you explain why, Cyborg Sun?). So, the powerups should not be removed, they should be fixed.
However, the two you show, Jordan, show random powerups, but not invulnerability, so these two are definitely not the ones.
I assume that the invulnerability powerups are those that require a specific combo, is that right, Cyborg Sun?

If we know that other invulnerability powerups, work on hard, but not on easy, we can check how they did it there.
But you have to check that on EASY, as I've seen many others with the combo powerup on normal, so I think they're supposed to work on normal. Except if that's not what Cyborg Sun means (I never play on hard).

**Comment by ak2yny** [comment]
> reputation points fix in asgard - [63b3828](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/63b3828fab252a7cac0a13ba88940b652b4a4cae)

About that issue:
Shouldn't it be in optional files? Because:
1. Solving puzzles should feel rewarding as well. I'm curious why this reward specifically should not be justified.
2. There are many rewards that appear completely random, I could never see a pattern how these work (I can't see any impact of them either).
If we're going to change reputation, we should make a rule what should give reputation, how much and why.

Btw. `rot_lever1_new.py` and `rot_lever2_new.py` are the only scripts used by the game. The other two are leftover.

**Comment by ak2yny** [comment]
While checking for awards, I noticed that reputation is typically given for defeating bosses, while side-quests and finding secrets gives XP. Here is a complete list of awards (through scripts, this excludes rewards that the .exe is responsible for):
```
Defeat Wrecking Crew:
conversations\act3\bifrost\bifrost2\3_bifrost2_030.engb
scripts/act3/bifrost/bifrost2/award_rep

scripts\act1\atlantis\atlantis4\boss_death.py:12:awardAchievement("", "defeated_tigershark" )
scripts\act1\atlantis\atlantis4\boss_death.py:13:awardReputation("", 50 )
scripts\act1\atlantis\atlantis5\challenge_win.py:60:     awardAchievement("", "defeated_kraken" )
scripts\act1\atlantis\atlantis5\challenge_win.py:61:     awardReputation("", 50 )
scripts\act1\heli\heli1\scorpion_deathscript.py:2:awardReputation("", 20 )
scripts\act1\heli\heli1b\scorpion_deathscript.py:2:awardReputation("", 300 )
scripts\act1\heli\heli2\bullseye_deathscript.PY:2:awardReputation("", 20 )
scripts\act1\heli\heli4\fff_death.py:7:awardAchievement("", "defeated_fingfangfoom" )
scripts\act1\heli\heli4\fff_pain.PY:62:               awardAchievement("", "defeated_fingfangfoom" )
scripts\act1\heli\heli4\fff_pain.PY:63:               awardReputation("", 50 )
scripts\act1\mandarin\mandarin1\dragon_death.PY:4:awardReputation("", 20 )
scripts\act1\mandarin\mandarin1\ultimo_death.PY:4:awardReputation("", 20 )
scripts\act1\mandarin\mandarin2\grey_defeat.py:6:awardReputation("", 50 )
scripts\act1\mandarin\mandarin2\grey_defeat.py:7:awardAchievement("", "defeated_greygargoyle" )
scripts\act1\mandarin\mandarin3\ultimo_death.PY:4:awardReputation("", 20 )
scripts\act1\mandarin\mandarin5\mandarin_leaves.PY:16:awardAchievement("", "defeated_mandarin" )
scripts\act1\mandarin\mandarin5\mandarin_leaves.PY:17:awardReputation("", 125 )
scripts\act1\omega\omega1\crimdeath.PY:4:awardReputation("", 20 )
scripts\act1\omega\omega4\modok_death_script.py:5:awardAchievement("", "defeated_modok" )
scripts\act1\omega\omega4\modok_death_script.py:6:awardReputation("", 50 )
scripts\act1\omega\omega4\modok_defeated.py:4:awardAchievement("", "defeated_modok" )
scripts\act1\omega\omega4\modok_defeated.py:5:awardReputation("", 50 )
scripts\act2\mephisto\mephisto3\blackheart_death.py:15:     awardAchievement("", "defeated_blackheart" )
scripts\act2\mephisto\mephisto3\blackheart_death.py:16:     awardReputation("", 50 )
scripts\act2\mephisto\mephisto4\hero_get_mephisto.PY:20:awardAchievement("", "defeated_mephisto" )
scripts\act2\mephisto\mephisto4\hero_get_mephisto.PY:22:awardReputation("", 125 )
scripts\act2\murder\murder5\boss_death.PY:5:awardAchievement("", "defeated_arcade" )
scripts\act2\murder\murder5\boss_death.PY:6:awardReputation("", 50 )
scripts\act2\strange\talk_weasel_intro03.PY:7:     awardXPToPlayable(1000 )
scripts\act3\asgard\asgard1\ench_exec_death.py:4:awardAchievement("", "defeated_executioner" )
scripts\act3\asgard\asgard1\ench_exec_death.py:5:awardReputation("", 50 )
scripts\act3\asgard\asgard2\rot_lever1.py:46:          awardReputation("", 5 )
scripts\act3\asgard\asgard2\rot_lever1_new.py:73:          awardReputation("", 5 )
scripts\act3\asgard\asgard2\rot_lever2.py:46:          awardReputation("", 5 )
scripts\act3\asgard\asgard2\rot_lever2_new.py:73:          awardReputation("", 5 )
scripts\act3\asgard\asgard4\havehornornot.py:4:# ( "If they found it, he awards them" )
scripts\act3\bifrost\bifrost2\award_rep.PY:3:awardReputation("", 100 )
scripts\act3\niffleheim\niffleheim2\ymir_death.py:4:awardAchievement("", "defeated_ymir" )
scripts\act3\niffleheim\niffleheim2\ymir_death.py:5:awardReputation("", 50 )
scripts\act3\niffleheim\niffleheim3\dococ_death.py:3:awardReputation("", 20 )
scripts\act3\niffleheim\niffleheim3\mordo_death.py:3:awardReputation("", 20 )
scripts\act3\niffleheim\niffleheim3\ultron_death.py:3:awardReputation("", 20 )
scripts\act3\niffleheim\niffleheim4\lokideath2.py:5:awardAchievement("", "defeated_loki" )
scripts\act3\niffleheim\niffleheim4\lokideath2.py:6:awardReputation("", 125 )
scripts\act3\valhalla\talk_weasel_intro03.PY:6:     awardXPToPlayable(5000 )
scripts\act4\attilan\crytstal_intro01.PY:8:     awardXPToPlayable(3500 )
scripts\act4\shiar\shiar2\gladiator_defeated.py:5:awardAchievement("", "defeated_gladiator" )
scripts\act4\shiar\shiar2\gladiator_defeated.py:6:awardReputation("", 50 )
scripts\act4\shiar\shiar4\deathbird_defeated.py:4:awardAchievement("", "defeated_deathbird" )
scripts\act4\shiar\shiar4\deathbird_done.PY:8:awardAchievement("", "defeated_deathbird" )
scripts\act4\shiar\shiar4\deathbird_done.PY:9:awardReputation("", 50 )
scripts\act4\skrull\skrull4\titannus_defeated.py:6:awardAchievement("", "defeated_titannus" )
scripts\act4\skrull\skrull4\titannus_defeated.py:7:awardReputation("", 50 )
scripts\act4\skrull\skrull5\all_done.PY:8:awardAchievement("", "defeated_galactus" )
scripts\act4\skrull\skrull5\stopnexus.py:61:     awardAchievement("", "defeated_galactus" )
scripts\act4\skrull\skrull5\surferchallenge_win.PY:66:     awardAchievement("", "defeated_galactus" )
scripts\act4\skrull\skrull5\surferchallenge_win.PY:67:     awardReputation("", 125 )
scripts\act5\doom\doom4\dark_machine_pain.py:13:     awardReputation("", 20 )
scripts\act5\doom\doom4\dspider_death.py:2:awardReputation("", 20 )
scripts\act5\doom\doom4\dthor_death.py:8:awardReputation("", 20 )
scripts\act5\doom\doom5\end_of_game.PY:5:awardAchievement("", "defeated_doom" )
scripts\act5\doom\doom5\end_of_game.PY:6:awardAchievement("", "unlocked_nickfury" )
scripts\act5\doom\doom5\end_of_game.PY:7:awardReputation("", 200 )
scripts\common\defeatnamedvillain.py:3:awardReputation("", 20 )
scripts\common\actionfigures\xpbonus.PY:3:awardXPToPlayable(5000 )
scripts\common\beacons\treasureact.py:3:awardXPToPlayable(5000 )
scripts\common\beacons\treasureact1.py:3:awardXPToPlayable(5000 )
scripts\common\beacons\treasureact2.py:3:awardXPToPlayable(15000 )
scripts\common\beacons\treasureact3.py:3:awardXPToPlayable(25000 )
scripts\common\beacons\treasureact4.py:3:awardXPToPlayable(35000 )
scripts\common\beacons\treasureact5.py:3:awardXPToPlayable(40000 )
scripts\common\conv_run_once\run_once17.py:9:          awardXPToPlayable(200 )
```
As you can see, reputation is given for defeating bosses, and objectives (two only?), except for the rotation lever. I believe it would be good to award between 200 and 1000 XP for this (provided it is for finding the shortcut).

**Comment by JordanLeich** [comment]
Fixed in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/5acbf263585376f39efe797f47684b17d4279a8e

**Comment by CyborgSun** [comment]
> The issue is that they also have invulnerability on easy, which they shouldn't (can you explain why, Cyborg Sun?). So, the powerups should not be removed, they should be fixed. However, the two you show, Jordan, show random powerups, but not invulnerability, so these two are definitely not the ones. I assume that the invulnerability powerups are those that require a specific combo, is that right, Cyborg Sun?
> 
> If we know that other invulnerability powerups, work on hard, but not on easy, we can check how they did it there. But you have to check that on EASY, as I've seen many others with the combo powerup on normal, so I think they're supposed to work on normal. Except if that's not what Cyborg Sun means (I never play on hard).

Invulnerability powerups are indeed the ones where you have to combo them, as well as different ones where they either give minions invincibility, or are only granted invincibility when near minions. They're not supposed to appear on both Easy and Normal, only Hard. (The others you see with invuln powerups on Normal were most likely the Viking Warriors, who give themselves the combo version of the invuln as a power; This function is normal, as it's a specific power they have, not a shared Leader powerup)

**Comment by CyborgSun** [comment]
OK, so about the Eye of the Shadow Queen: No matter what changes had been made to it, it still doesn't seem to really work right for me (as in, it's still unable to be completed after you beat the main mission, and need to portal back during the mission, which seems to disable the speech Fury gives at the end after the main mission is done).

At this rate, I think it should just be reverted back to the way it worked before (the objective instantly completing after you pick it up, even if it "doesn't make sense"). Seems like Raven made it work this way for a good reason, lol.

**Comment by JordanLeich** [comment]
> OK, so about the Eye of the Shadow Queen: No matter what changes had been made to it, it still doesn't seem to really work right for me (as in, it's still unable to be completed after you beat the main mission, and need to portal back during the mission, which seems to disable the speech Fury gives at the end after the main mission is done... uh, do you follow me?).
> 
> At this rate, I think it should just be reverted back to the way it worked before in the base, unmodded game (the objective instantly completing after you pick it up, even if it "doesn't make sense"). Seems like Raven made it work this way for a good reason, lol.

I can confirm both instances as I've just tested them. The obj only completes if you portal back to the sanctum and talk to Wong but then doing this will make Furys conversation not play when completing the defeat mephisto mission. Also, if you pickup the orb but dont portal back to give it to wong and do the mission as normal, when you get back to the sanctum and talk to wong, the dialogue for bringing the orb back to him doesnt play and thus you cant complete the obj. I'd say we have two options to go about fixing this issue:
Either we try again to fix the issue to where your allow to portal back and complete the obj + hear the fury dialogue after killing mephisto but this likely wont work due to how the portal is handled? or we go back to vanilla like @CyborgSun said, have the orb pickup complete the obj and just fix the obj description to not say return back to Wong. But if we do it this way, will Wong's special dialogue still play for returning the orb after killing Mephisto or no?

**Comment by CyborgSun** [comment]
> But if we do it this way, will Wong's special dialogue still play for returning the orb after killing Mephisto or no?

I can confirm that this specific dialogue doesn't play in vanilla after killing Mephisto. Similar to what you suggested though, you could change the description to say something akin to "The Eye will teleport itself back to Wong" or something. I don't think anyone else really cares that much for the story making sense for this one thing, but it'd be neat to have a short little explanation in case someone does care enough.

**Comment by JordanLeich** [comment]
> I can confirm that this specific dialogue doesn't play in vanilla after killing Mephisto. Similar to what you suggested though, you could change the description to say something akin to "The Eye will teleport itself back to Wong" or something. I don't think anyone else really cares that much for the story making sense for this one thing, but it'd be neat to have a short little explanation in case someone does care enough.

So then his special dialogue for bringing it back to him will be unused and can be removed?

**Comment by CyborgSun** [comment]
> So then his special dialogue for bringing it back to him will be unused and can be removed?

Yeah, I say it's best to do that. Removing it outright would lower the triggers of that HUB just a tiny bit, but every bit helps.

**Comment by JordanLeich** [comment]
I managed to fix it in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/fab1a04c911bf16806d41770b426fc87281f537e @CyborgSun, @ak2yny had the script .py file in the wrong location and I can confirm it works now.

**Comment by CyborgSun** [comment]
updated the report with a little Asgard thing I found

**Comment by JordanLeich** [comment]
> updated the report with a little Asgard thing I found

Fixed in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/34d69f20cc4dcfdbc2350fa59f3daa6a3e4e343a

**Comment by CyborgSun** [comment]
I've discovered the cause of Ultimate Iron Man's loadscreen issue:

The file **is** in the game, but its name is 1504. The game (well, this version of the game at least) can't go above 3 for loadscreens. To fix this, it can simply be renamed to 1502 (I guess meaning a copy of the file with this name will have to be provided in the OCP). However, to get it to unlock in the Review menu as well, the "review_paths.engb" file has to be modified to have Ultimate Iron Man point to 1502, since that also uses the 1504 number. Doing all this, not only will the screen actually appear, but is unlocked as well (trust me that latter part actually does matter to me as a completionist lmao).

**Comment by ak2yny** [comment]
That makes sense, thank you. Since skin numbers 1502 and 1503 both are taken, but both are still free in terms of LS, which number should each skin be changed to? (I assume that it would be best to leave the slots as they are, which will be easier, too, because we don't need to change the talents file.)

```
   skin = 1502 ;
   skin_01_name = New Avengers ;
   skin_02 = 05 ;
   skin_02_name = Classic ;
   skin_03 = 03 ;
   skin_03_name = War Machine ;
   skin_04 = 04 ;
   skin_04_name = Ultimate ;
```

**Comment by CyborgSun** [comment]
Nothing needs to be done to the skin numbers, it's just the loadscreen file and review_paths.engb that needs to be changed. Like I said, it's probably easiest to just have a copy of the 1504.igb loadscreen renamed to 1502.igb provided in the OCP, while also making sure that other file is changed so that the new "1502" file is actually unlocked in the Review menu.

**Comment by CyborgSun** [comment]
Oh, and there are a couple other things I want to point out:

For the Moon Knight and Colossus loadscreens, I've found they don't show up when beginning a simulator solo as them (showing the more generic Galactus one instead), but they do show up in the results screen. This is quite an unusual case, but it could be some weirdness caused by their original "next-gen exclusive" status. So, I'm not even sure if them not showing up "normally" even CAN be fixed, unless there's some obscure file in the game that's secretly controlling that which is also easy to edit.

Using the EXG, Jean Grey still becomes Defaultman in the areas mentioned above. Just pointing that out in the hopes you can collaborate with Outsider to help fix that.

**Comment by JordanLeich** [comment]
> > [...] while also making sure that other file is changed so that the new "1502" file is actually unlocked in the Review menu.
> 
> Thank you very much. What other file are you referring to?

I'm assuming review_paths.engb

**Comment by CyborgSun** [comment]
Yeah, I thought I made that clear but oh well. Anyways, I already provided the fix up above, so you guys can just go ahead and use that.

**Comment by ak2yny** [comment]
The Outsider recently confirmed the Colossus and MK LS issue and specified that mods with the same number (78 and 41) also don't show the LS. I gave it some thought and searched the files. I found one that could be connected (loading menu IIRC), but none that specifically reference the LS or numbers. The OCP2 already removes any Colossus and MK references that would prevent them from being fully playable. I came to the conclusion that the game.exe controls this. It probably iterates through the numbers (0 to 255), and excludes 78 and 41 (which would be in bytes, or 4E and 29 in hex). There are many occurrences for each, so this is a hard one to find without disassembling the .exe.
I made it a separate issue.
